add_newline = false

[character]
success_symbol = "â¯"
error_symbol = "â¯"

[git_branch]
symbol = "î‚  "

[nodejs]
symbol = "â¬¢ "

[rust]
symbol = "ğŸ¦€ "

[python]
symbol = "ğŸ "

[azure]
disabled = false
